### ISSUE TITLE
"python2" not necessarily in the path

### ISSUE THREAD

**Issue by nomeata** [nushio3/cmaes#1]
The cma.py file that you ship calls to python2, but e.g. on Debian, there is no binary of that name. Here, just "python" starts python 2.7. This makes your library fail with a not very helpful error message.

**Comment by nushio3** [comment]
Oh, My. Is there any environment-independent way to detect python 2.x?

**Comment by nomeata** [comment]
After some quick googling, I did not find one. Maybe this would be a useful question on stackexchange?

**Comment by nh2** [comment]
`python --version`. If its >= 3, use `python2`.

**Comment by nushio3** [comment]
Let me see, I have to locate and rewrite cma.py at runtime. That's not so difficult than I've expected. Let me try.

**Comment by nushio3** [comment]
https://github.com/nushio3/cmaes/commit/d595cd79e4b573e8a7d571da1313b99016fa4824

A mechanism that detects the python version and inserts a shebang that works hopefully on more broader context.

Thank you for your contributions, and I'm sorry for the delay in the update.

I wish this library is useful to you :)
